### ISSUE TITLE
software crash for RECORD_LAYOUT

### ISSUE THREAD

**Issue by xujinpeng1117** [kallemooo/Asap2#7]
Hi:

Thanks for you lib!

I found software crash when a2l include following txt:
    /begin RECORD_LAYOUT SWORD_COL_DIRECT 
      FNC_VALUES 1 SWORD COLUMN_DIR DIRECT
      ALIGNMENT_WORD 2
      ALIGNMENT_LONG 2
      ALIGNMENT_FLOAT32_IEEE 2
      ALIGNMENT_FLOAT64_IEEE 4
    /end RECORD_LAYOUT

It seems the problem come from Asap2Files.cs   line 816
        [Element(1, IsDictionary = true)]
        public Dictionary<string, ALIGNMENT> alignments;
So I change it to :
        [Element(1, IsDictionary = true)]
        public Dictionary<string, ALIGNMENT> alignments = new Dictionary<string, ALIGNMENT>();

The software can work normally now. Is my modification correct?

**Comment by kallemooo** [comment]
Yes.

That is correct fix.
