### ISSUE TITLE
Identifier RESERVED (PrgType) cannot be parsed inside MEMORY_SEGMENT

### ISSUE THREAD

**Issue by AndreasLehnerCDE** [kallemooo/Asap2#8]
The grammar is identifying the RESERVED PrgType as token which makes the parser fail.
E.x.: (I renamed the segment name and description)
/begin MEMORY_SEGMENT nameofsegment "description" RESERVED

The error from the library: 
… Line: 926 : Row: 66 : Syntax error, unexpected RESERVED, expecting IDENTIFIER

**Comment by CoppaLoccioni** [comment]
@AndreasLehnerCDE Have you found a solution for this?

**Comment by AndreasLehnerCDE** [comment]
@CoppaLoccioni No I did not find a solution. Do you have this problem as well?

**Comment by CoppaLoccioni** [comment]
@AndreasLehnerCDE yes same issue

**Comment by kallemooo** [comment]
This problem requires special treatment in parser grammar. A patch for the problem is pending.
